name: Deploy Flask App to Heroku

on:
  push:
    branches:
      - main  # or master, depending on your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # The GitHub runner environment

    steps:
    # Step 1: Checkout code from GitHub repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # You can specify a version like '3.9'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Deploy to Heroku using Heroku Action
    - name: Deploy to Heroku
      uses: akshnz/heroku-action@v0.1.0  # Corrected Action
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: your-heroku-app-name
        heroku_email: your-email@example.com
